// var container = '1' //declare variable string, kalau angka jangan pakai petik. nanti angkanya jadi string
// var, let , const ini adalah untuk mendeclare variable
// kalau pakai LET ga bisa ditulis 2x. karena nanti akan error. 
// kalau declare var 2x, yang kebaca yang dibawah. 
// CONST harus yang tetap, kalau di declare lagi tidak akan bisa
// let container = '2' // kalau ada 2 petik dalam 1 kalimat bisa menggunakan +
// e.g "Batman's city is called" + '"gotham"'
// container = 2
// console.log(container)

// let city = '"Gotham"'
// let owner = "Batman"
// console.log(city + ' is the city ' + owner) // setelah petik pakai spasi biar tulisannya ga dempet dempet
// panggil variable yang mau dipanggil + panggil lagi variable yang mau dipanggil
// let city = '"gotham"'
// let owner = "batman"
// console.log (city, owner)

// let satu = 1
// let tiga = 3
// console.log(satu + tiga)
// kalau mau pake + untuk operasional, pas di declare jangan pakai tanda ''
// let response = '1000000'
// let pajak = 5000
// console.log(parseInt(response))
// harus bilangan bulat, karena menggunakan parseInt 
// kalau pakai parseFloat kalau ada decimal
